version: "3.9"

services:
  web:
    build: .
#    command: gunicorn django_project.wsgi -b 0.0.0.0:8000
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/repositories:Z
    ports:
      - 8000:8000
    depends_on:
      - db
#    environment:
#      - "DJANGO_SECRET_KEY=twfEqm68oqIrxYxflNvRFooGCkBxbQC6CsIiYnX9IXY55OAQ07k"

  db:
    image: postgres:13
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgresql_data: