version: "3.9"

services:
  web:
    build: .
    command: gunicorn django_project.wsgi -b 0.0.0.0:8000
    volumes:
      - .:/repositories:Z
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      # Settings below are for local development only!
      - "SECRET_KEY=django-insecure-aujsk&3mt2w4r-0vkvzzuk)jhx(b-c5$j^qc4#ecz2t_8hwgq-"
      - "DEBUG=True"

  db:
    image: postgres:13
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgresql_data: