# Generated by Django 4.2.16 on 2024-09-08 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driving_logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drive',
            name='date',
            field=models.DateField(),
        ),
    ]
