# Generated by Django 4.2.16 on 2024-09-08 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driving_logs', '0002_alter_drive_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivinglog',
            name='name',
            field=models.CharField(default='default', max_length=255),
        ),
    ]
