# Generated by Django 4.2.16 on 2024-09-10 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driving_logs', '0003_drivinglog_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='drive',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
